### ISSUE TITLE
Bug: error 500 when create feed php 7

### ISSUE THREAD

**Issue by centoasa** [numinix/google_merchant_center#11]
with php 7 when generate feed, have error 500 with these spec:
googlefroogle.php?feed=fy_un_tp&limit=&offset=&x=15&y=14&key=60f688be81

**Comment by RobNuminix** [comment]
Zen Cart and our plugins are not yet compatible with php 7.  When Zen Cart
v1.6 comes out with compatibility we will also ensure our plugins are
compatible.
